FROM python:3.12-slim AS base

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-node.txt /

RUN pip install --upgrade pip \
    && pip install -r /requirements-node.txt

RUN ape plugins install infura

ENTRYPOINT [ "/bin/bash" ]
