dotenv: .env

networks:
  default: development
  sepolia:
    host: 'https://sepolia.infura.io/v3/${WEB3_INFURA_PROJECT_ID}'
    name: 'sepolia'
    chainid: 11155111
    explorer: 'https://sepolia.etherscan.io'

wallets:
  from_key: ${PRIVATE_KEY}

dependencies: []

compiler:
  solc:
    remappings: []